<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AssemblyName>MailLoadTester</AssemblyName>
    <RootNamespace>MailLoadTester.Gui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MailLoadTester.Core\MailLoadTester.Core.csproj" />
  </ItemGroup>
</Project>
